### ISSUE TITLE
EID Registration and Verification

### ISSUE THREAD

**Issue by sekrantz** [BlueBiteLLC/escaconfig-ios#3]
Issue to track all the steps required for registration and verification for Eddystone EID support.

**Comment by djskripta** [comment]
Steps:

- GET v2/tags/eid/eidparams (get public key with min and max rotation exponent)
- ```call('POST', 'v2/tags/eid/beacons:register', [
            'app_key' => 'APP_KEY_HERE',
            'tag_id' => MTAG_ID, //eg. 12345678 (we need this to generate the url)
            'advertisedId' => [
                'type' => 'EDDYSTONE', //"stable" Eddystone-UID
                'id' => TAG_UID, //converted from hex to binary, then base64 encoded
            ],
            'status' => 'ACTIVE',
            'ephemeralIdRegistration' => [
                'beaconEcdhPublicKey' => $beacon_keypair['public'],
                'serviceEcdhPublicKey' => $public_key, //returned in the first api call
                'rotationPeriodExponent' => $scaler, //chosen based on min and max returned be service
                'initialClockValue' => $beacon_time,
                'initialEid' => $eid, //initial EID
            ],
        ]);```
- Now attach something to the beacon
        ```call('POST', 'v2/tags/eid/' . $content['beaconName'] . '/attachments', [
            'app_key' => $app_key->key,
            'namespacedType' => 'url',
            'data' => base64_encode($content['properties']['url']), //$content is the response from the api call above - that call generates a url property
        ]);```

When you want to check the beacon data, you can either:
- ```call('POST', 'v2/tags/eid/beaconinfo:getforobserved', [
            'app_key' => $app_key->key,
            'observations' => [
                [
                    'advertisedId' => [
                        'type' => 'EDDYSTONE_EID',
                        'id' => $eid,
                    ],
                    'telemetry' => '',
                    'timestampMs' => date('Y-m-d\TH:i:s') . '.000000000Z', //Zulu time
                ],
            ],
            'namespacedTypes' => ['*'],
        ]);```
- Go to the tag url, with an extra ?vid=CURRENT_EID_HERE parameter (if the tag is set up in dragonfish to use EID verification, it will not show the experience unless the EID gets successfully verified.. I am setting up for BlueBiteLLC/system-narwhale#1034)

**Comment by sekrantz** [comment]
Thanks for the writeup!  I've just got a few questions about the routes.

POST: `“v2/tags/eid/beacons:register”`

1. For `advertisedId[id]` by TAG_UID do you mean the Eddystone UID?

POST: `“v2/tags/eid/“ + <beaconName> + “/attachments”`

2. What do you mean by `beaconName`?  the MTAG_ID?  The Eddystone UID?  Or is it part of the response from `v2/tags/eid/beacons:register`?
3. For `namespacedType` the url you want is the beacon’s eddystone URL right?  (`esca.io/e…`)?
    - If so, do you want it as just `esca.io/e...` or as `https://esca.io/e...` or the `URL frame` advertised by the beacon?
4. Can you clarify what you mean by attach something to the beacon?  Is this a call that allows me to define a URL that will be served as a response to `v2/tags/eid/beaconinfo:getforobserved`?
5. `data` is the response from registering the beacon initially, but doesn’t that mean we can only attach things to the beacon during initial registration?


POST : `“v2/tags/eid/beaconinfo:getforobserved”`:

6. For `telemetry` do you want the entire TLM frame or just the beacon's `onTime`?
7. For `timestampMs` can you provide me with an example of how the time would look formatted this way?
    - Is it like `2016-08-18EST10:32:23.000000000-14400`?
8. Is `observations` supposed to be a nested array?
    - As of now I’d be passing in `observations : [ [advertiseId[…], telemetry, timestampMs] ]`  Wouldn't `observations: [advertisedId[...], telemetry, timestampMs]` work equally as well?  It seems like the outer array is superfluous.  Obviously I can format it with the outer array if you need it on your end, I just want to make sure I'm not misunderstanding something.
9. Can you clarify what you need for `namespacedTypes` and what its purpose is?

**Comment by djskripta** [comment]
1.1 - yes
2.1 - `$content is the response from the api call`
2.2 - `'namespacedType' => 'url'` - no vars just a static string
2.3 - yes
2.4 - we pass the url from the response into `data` so the client doesnt have to generate the url
3.1 - i m not sure about telemetry, but i think it can be the tlm frame.. can also be empty
3.2 - `2014-10-02T15:01:23.045123456Z`
3.3 - it's formatted as documented by google api.. yes, nested array
3.4. - namespacedTypes determines which beacon namespaces it pulls from .. i think there is only the `beacons` namespace, but google requires this param.. `*` just means for it to look in all namespaces
